from fastapi import FastAPI
app = FastAPI()

paises = [{"nombre": "República Islámica de Afganistán(Afganistán)", "continente": "Asia", "capital": "Kabul"},
{"nombre": "República de Albania(Albania)", "continente": "Europa", "capital": "Tirana"},
{"nombre": "República Federal de Alemania(Alemania)", "continente": "Europa", "capital": "Berlín"},
{"nombre": "Principado de Andorra(Andorra)", "continente": "Europa", "capital": "Andorra la Vieja"},
{"nombre": "República de Angola(Angola)", "continente": "África", "capital": "Luanda"},
{"nombre": "Antigua y Barbuda", "continente": "América", "capital": "Saint John"},
{"nombre": "Reino de Arabia Saudita(Arabia Saudita/Arabia Saudí)", "continente": "Asia", "capital": "Riad"},
{"nombre": "República Argelina Democrática y Popular(Argelia)", "continente": "África", "capital": "Argel"},
{"nombre": "República Argentina(Argentina)", "continente": "América", "capital": "Buenos Aires"},
{"nombre": "República de Armenia(Armenia)", "continente": "Asia-Europa", "capital": "Ereván"},
{"nombre": "Mancomunidad de Australia(Australia)", "continente": "Oceanía", "capital": "Canberra"},
{"nombre": "República de Austria(Austria)", "continente": "Europa", "capital": "Viena"},
{"nombre": "República de Azerbaiyán(Azerbaiyán)", "continente": "Asia-Europa", "capital": "Bakú"},
{"nombre": "Mancomunidad de las Bahamas(Bahamas)", "continente": "América", "capital": "Nasáu"},
{"nombre": "República Popular de Bangladés(Bangladés)", "continente": "Asia", "capital": "Daca"},
{"nombre": "Barbados", "continente": "América", "capital": "Bridgetown"},
{"nombre": "Reino de Baréin(Baréin)", "continente": "Asia", "capital": "Manama"},
{"nombre": "Reino de Bélgica(Bélgica)", "continente": "Europa", "capital": "Bruselas"},
{"nombre": "Belice", "continente": "América", "capital": "Belmopán"},
{"nombre": "República de Benín(Benín)", "continente": "África", "capital": "Porto Novo"},
{"nombre": "República de Bielorrusia(Bielorrusia)", "continente": "Europa", "capital": "Minsk"},
{"nombre": "República de la Unión de Myanmar(Birmania/Myanmar)", "continente": "Asia", "capital": "Naipyidó"},
{"nombre": "Estado Plurinacional de Bolivia(Bolivia)", "continente": "América", "capital": "Sucre"},
{"nombre": "Bosnia y Herzegovina(Bosnia y Herzegovina/Bosnia-Herzegovina)", "continente": "Europa", "capital": "Sarajevo"},
{"nombre": "República de Botsuana(Botsuana)", "continente": "África", "capital": "Gaborone"},
{"nombre": "República Federativa del Brasil(Brasil)", "continente": "América", "capital": "Brasilia"},
{"nombre": "Estado de Brunéi Darussalam(Brunéi)", "continente": "Asia", "capital": "Bandar Seri Begawan"},
{"nombre": "República de Bulgaria(Bulgaria)", "continente": "Europa", "capital": "Sofía"},
{"nombre": "Burkina Faso", "continente": "África", "capital": "Uagadugú"},
{"nombre": "República de Burundi(Burundi)", "continente": "África", "capital": "Gitega"},
{"nombre": "Reino de Bután(Bután)", "continente": "Asia", "capital": "Timbu"},
{"nombre": "República de Cabo Verde(Cabo Verde)", "continente": "África", "capital": "Praia"},
{"nombre": "Reino de Camboya(Camboya)", "continente": "Asia", "capital": "Nom Pen"},
{"nombre": "República de Camerún(Camerún)", "continente": "África", "capital": "Yaundé"},
{"nombre": "Canadá", "continente": "América", "capital": "Ottawa"},
{"nombre": "Estado de Catar(Catar)", "continente": "Asia", "capital": "Doha"},
{"nombre": "República Centroafricana", "continente": "África", "capital": "Bangui"},
{"nombre": "República del Chad(Chad)", "continente": "África", "capital": "Yamena"},
{"nombre": "República Checa(República Checa/Chequia)", "continente": "Europa", "capital": "Praga"},
{"nombre": "República de Chile(Chile)", "continente": "América", "capital": "Santiago de Chile"},
{"nombre": "República Popular China(China)", "continente": "Asia", "capital": "Pekín"},
{"nombre": "República de Chipre(Chipre)", "continente": "Europa-Asia", "capital": "Nicosia"},
{"nombre": "República de Colombia(Colombia)", "continente": "América", "capital": "Bogotá"},
{"nombre": "Unión de las Comoras(Comoras)", "continente": "África", "capital": "Moroni"},
{"nombre": "República del Congo", "continente": "África", "capital": "Brazzaville"},
{"nombre": "República Democrática del Congo", "continente": "África", "capital": "Kinsasa"},
{"nombre": "República Popular Democrática de Corea(Corea del Norte)", "continente": "Asia", "capital": "Pionyang"},
{"nombre": "República de Corea(Corea del Sur)", "continente": "Asia", "capital": "Seúl"},
{"nombre": "República de Costa de Marfil(Costa de Marfil)", "continente": "África", "capital": "Yamusukro"},
{"nombre": "República de Costa Rica(Costa Rica)", "continente": "América", "capital": "San José"},
{"nombre": "República de Croacia(Croacia)", "continente": "Europa", "capital": "Zagreb"},
{"nombre": "República de Cuba(Cuba)", "continente": "América", "capital": "La Habana"},
{"nombre": "Reino de Dinamarca(Dinamarca)", "continente": "Europa", "capital": "Copenhague"},
{"nombre": "Mancomunidad de Dominica(Dominica)", "continente": "América", "capital": "Roseau"},
{"nombre": "República Dominicana", "continente": "América", "capital": "Santo Domingo"},
{"nombre": "República del Ecuador(Ecuador)", "continente": "América", "capital": "Quito"},
{"nombre": "República Árabe de Egipto(Egipto)", "continente": "África-Asia", "capital": "El Cairo"},
{"nombre": "República de El Salvador(El Salvador)", "continente": "América", "capital": "San Salvador"},
{"nombre": "Emiratos Árabes Unidos", "continente": "Asia", "capital": "Abu Dabi"},
{"nombre": "Estado de Eritrea(Eritrea)", "continente": "África", "capital": "Asmara"},
{"nombre": "República Eslovaca(Eslovaquia)", "continente": "Europa", "capital": "Bratislava"},
{"nombre": "República de Eslovenia(Eslovenia)", "continente": "Europa", "capital": "Liubliana"},
{"nombre": "Reino de España(España)", "continente": "Europa", "capital": "Madrid"},
{"nombre": "Estados Unidos de América(Estados Unidos)", "continente": "América", "capital": "Washington D.C."},
{"nombre": "República de Estonia(Estonia)", "continente": "Europa", "capital": "Tallin"},
{"nombre": "República Democrática Federal de Etiopía(Etiopía)", "continente": "África", "capital": "Adís Abeba"},
{"nombre": "República de Filipinas(Filipinas)", "continente": "Asia", "capital": "Manila"},
{"nombre": "República de Finlandia(Finlandia)", "continente": "Europa", "capital": "Helsinki"},
{"nombre": "República de Fiyi(Fiyi)", "continente": "Oceanía", "capital": "Suva"},
{"nombre": "República Francesa(Francia)", "continente": "Europa", "capital": "París"},
{"nombre": "República Gabonesa(Gabón)", "continente": "África", "capital": "Libreville"},
{"nombre": "República del Gambia(Gambia)", "continente": "África", "capital": "Banjul"},
{"nombre": "Georgia", "continente": "Asia-Europa", "capital": "Tiflis"},
{"nombre": "República de Ghana(Ghana)", "continente": "África", "capital": "Acra"},
{"nombre": "Granada", "continente": "América", "capital": "Saint George"},
{"nombre": "República Helénica(Grecia)", "continente": "Europa", "capital": "Atenas"},
{"nombre": "República de Guatemala(Guatemala)", "continente": "América", "capital": "Ciudad de Guatemala"},
{"nombre": "República de Guinea(Guinea)", "continente": "África", "capital": "Conakry"},
{"nombre": "República de Guinea-Bisáu(Guinea-Bisáu)", "continente": "África", "capital": "Bisáu"},
{"nombre": "República de Guinea Ecuatorial(Guinea Ecuatorial)", "continente": "África", "capital": "Malabo"},
{"nombre": "República Cooperativa de Guyana(Guyana)", "continente": "América", "capital": "Georgetown"},
{"nombre": "República de Haití(Haití)", "continente": "América", "capital": "Puerto Príncipe"},
{"nombre": "República de Honduras(Honduras)", "continente": "América", "capital": "Tegucigalpa"},
{"nombre": "Hungría", "continente": "Europa", "capital": "Budapest"},
{"nombre": "República de la India(India)", "continente": "Asia", "capital": "Nueva Delhi"},
{"nombre": "República de Indonesia(Indonesia)", "continente": "Asia", "capital": "Yakarta"},
{"nombre": "República de Irak(Irak)", "continente": "Asia", "capital": "Bagdad"},
{"nombre": "República Islámica de Irán(Irán)", "continente": "Asia", "capital": "Teherán"},
{"nombre": "República de Irlanda(Irlanda)", "continente": "Europa", "capital": "Dublín"},
{"nombre": "República de Islandia(Islandia)", "continente": "Europa", "capital": "Reikiavik"},
{"nombre": "Estado de Israel(Israel)", "continente": "Asia", "capital": "oficial: Jerusalénde facto: Tel Aviv"},
{"nombre": "República Italiana(Italia)", "continente": "Europa", "capital": "Roma"},
{"nombre": "Jamaica", "continente": "América", "capital": "Kingston"},
{"nombre": "Estado del Japón(Japón)", "continente": "Asia", "capital": "Tokio"},
{"nombre": "Reino Hachemita de Jordania(Jordania)", "continente": "Asia", "capital": "Amán"},
{"nombre": "República de Kazajistán(Kazajistán)", "continente": "Asia-Europa", "capital": "Astaná"},
{"nombre": "República de Kenia(Kenia)", "continente": "África", "capital": "Nairobi"},
{"nombre": "República Kirguisa(Kirguistán)", "continente": "Asia", "capital": "Biskek"},
{"nombre": "República de Kiribati(Kiribati)", "continente": "Oceanía", "capital": "Tarawa Sur"},
{"nombre": "Estado de Kuwait(Kuwait)", "continente": "Asia", "capital": "Ciudad de Kuwait"},
{"nombre": "República Democrática Popular Lao(Laos)", "continente": "Asia", "capital": "Vientián"},
{"nombre": "Reino de Lesoto(Lesoto)", "continente": "África", "capital": "Maseru"},
{"nombre": "República de Letonia(Letonia)", "continente": "Europa", "capital": "Riga"},
{"nombre": "República Libanesa(Líbano)", "continente": "Asia", "capital": "Beirut"},
{"nombre": "República de Liberia(Liberia)", "continente": "África", "capital": "Monrovia"},
{"nombre": "Estado de Libia(Libia)", "continente": "África", "capital": "Trípoli"},
{"nombre": "Principado de Liechtenstein(Liechtenstein)", "continente": "Europa", "capital": "Vaduz"},
{"nombre": "República de Lituania(Lituania)", "continente": "Europa", "capital": "Vilna"},
{"nombre": "Gran Ducado de Luxemburgo(Luxemburgo)", "continente": "Europa", "capital": "Ciudad de Luxemburgo"},
{"nombre": "República de Macedonia del Norte(Macedonia del Norte)", "continente": "Europa", "capital": "Skopie"},
{"nombre": "República de Madagascar(Madagascar)", "continente": "África", "capital": "Antananarivo"},
{"nombre": "Federación de Malasia(Malasia)", "continente": "Asia", "capital": "Kuala Lumpur"},
{"nombre": "República de Malaui(Malaui)", "continente": "África", "capital": "Lilongüe"},
{"nombre": "República de Maldivas(Maldivas)", "continente": "Asia", "capital": "Malé"},
{"nombre": "República de Malí(Mali/Malí)", "continente": "África", "capital": "Bamako"},
{"nombre": "República de Malta(Malta)", "continente": "Europa", "capital": "La Valeta"},
{"nombre": "Reino de Marruecos(Marruecos)", "continente": "África", "capital": "Rabat"},
{"nombre": "República de las Islas Marshall(Islas Marshall)", "continente": "Oceanía", "capital": "Majuro"},
{"nombre": "República de Mauricio(Mauricio)", "continente": "África", "capital": "Port Louis"},
{"nombre": "República Islámica de Mauritania(Mauritania)", "continente": "África", "capital": "Nuakchot"},
{"nombre": "Estados Unidos Mexicanos(México)", "continente": "América", "capital": "Ciudad de México"},
{"nombre": "Estados Federados de Micronesia(Micronesia)", "continente": "Oceanía", "capital": "Palikir"},
{"nombre": "República de Moldavia(Moldavia)", "continente": "Europa", "capital": "Chisináu"},
{"nombre": "Principado de Mónaco(Mónaco)", "continente": "Europa", "capital": "Ciudad de Mónaco"},
{"nombre": "Mongolia(Mongolia)", "continente": "Asia", "capital": "Ulán Bator"},
{"nombre": "República de Montenegro(Montenegro)", "continente": "Europa", "capital": "Podgorica"},
{"nombre": "República de Mozambique(Mozambique)", "continente": "África", "capital": "Maputo"},
{"nombre": "República de Namibia(Namibia)", "continente": "África", "capital": "Windhoek"},
{"nombre": "República de Nauru(Nauru)", "continente": "Oceanía", "capital": "Yaren"},
{"nombre": "República Federal Democrática de Nepal(Nepal)", "continente": "Asia", "capital": "Katmandú"},
{"nombre": "República de Nicaragua(Nicaragua)", "continente": "América", "capital": "Managua"},
{"nombre": "República del Níger(Níger)", "continente": "África", "capital": "Niamey"},
{"nombre": "República Federal de Nigeria(Nigeria)", "continente": "África", "capital": "Abuya"},
{"nombre": "Reino de Noruega(Noruega)", "continente": "Europa", "capital": "Oslo"},
{"nombre": "Nueva Zelanda(Nueva Zelanda)", "continente": "Oceanía", "capital": "Wellington"},
{"nombre": "Sultanato de Omán(Omán)", "continente": "Asia", "capital": "Mascate"},
{"nombre": "Reino de los Países Bajos(Países Bajos)", "continente": "Europa", "capital": "Ámsterdam"},
{"nombre": "República Islámica de Pakistán(Pakistán)", "continente": "Asia", "capital": "Islamabad"},
{"nombre": "República de Palaos(Palaos)", "continente": "Oceanía", "capital": "Ngerulmud"},
{"nombre": "Estado de Palestina(Palestina)", "continente": "Asia", "capital": "oficial: Jerusalén Estede facto: Ramala"},
{"nombre": "República de Panamá(Panamá)", "continente": "América", "capital": "Ciudad de Panamá"},
{"nombre": "Estado Independiente de Papúa Nueva Guinea(Papúa Nueva Guinea)", "continente": "Oceanía", "capital": "Puerto Moresby"},
{"nombre": "República del Paraguay(Paraguay)", "continente": "América", "capital": "Asunción"},
{"nombre": "República del Perú(Perú)", "continente": "América", "capital": "Lima"},
{"nombre": "República de Polonia(Polonia)", "continente": "Europa", "capital": "Varsovia"},
{"nombre": "República Portuguesa(Portugal)", "continente": "Europa", "capital": "Lisboa"},
{"nombre": "Reino Unido de Gran Bretaña e Irlanda del Norte(Reino Unido)", "continente": "Europa", "capital": "Londres"},
{"nombre": "República de Ruanda(Ruanda)", "continente": "África", "capital": "Kigali"},
{"nombre": "Rumania(Rumania/Rumanía)", "continente": "Europa", "capital": "Bucarest"},
{"nombre": "Federación de Rusia(Rusia)", "continente": "Europa-Asia", "capital": "Moscú"},
{"nombre": "Islas Salomón(Islas Salomón)", "continente": "Oceanía", "capital": "Honiara"},
{"nombre": "Estado Independiente de Samoa(Samoa)", "continente": "Oceanía", "capital": "Apia"},
{"nombre": "Federación de San Cristóbal y Nieves(San Cristóbal y Nieves)", "continente": "América", "capital": "Basseterre"},
{"nombre": "Serenísima República de San Marino(San Marino)", "continente": "Europa", "capital": "Ciudad de San Marino"},
{"nombre": "San Vicente y las Granadinas(San Vicente y las Granadinas)", "continente": "América", "capital": "Kingstown"},
{"nombre": "Santa Lucía", "continente": "América", "capital": "Castries"},
{"nombre": "República Democrática de Santo Tomé y Príncipe(Santo Tomé y Príncipe)", "continente": "África", "capital": "Santo Tomé"},
{"nombre": "República de Senegal(Senegal)", "continente": "África", "capital": "Dakar"},
{"nombre": "República de Serbia(Serbia)", "continente": "Europa", "capital": "Belgrado"},
{"nombre": "República de las Seychelles(Seychelles)", "continente": "África", "capital": "Victoria"},
{"nombre": "República de Sierra Leona(Sierra Leona)", "continente": "África", "capital": "Freetown"},
{"nombre": "República de Singapur(Singapur)", "continente": "Asia", "capital": "Ciudad de Singapur"},
{"nombre": "República Árabe Siria(Siria)", "continente": "Asia", "capital": "Damasco"},
{"nombre": "República Federal de Somalia(Somalia)", "continente": "África", "capital": "Mogadiscio"},
{"nombre": "República Democrática Socialista de Sri Lanka(Sri Lanka)", "continente": "Asia", "capital": "Sri Jayawardenapura/Kotte[31]​"},
{"nombre": "Reino de Suazilandia(Suazilandia/Esuatini)", "continente": "África", "capital": "Mbabane"},
{"nombre": "República de Sudáfrica(Sudáfrica)", "continente": "África", "capital": "Pretoria (ejecutiva)Bloemfontein (judicial)Ciudad del Cabo (legislativa)"},
{"nombre": "República del Sudán(Sudán)", "continente": "África", "capital": "Jartum"},
{"nombre": "República de Sudán del Sur(Sudán del Sur)", "continente": "África", "capital": "Juba"},
{"nombre": "Reino de Suecia(Suecia)", "continente": "Europa", "capital": "Estocolmo"},
{"nombre": "Confederación Suiza(Suiza)", "continente": "Europa", "capital": "Berna"},
{"nombre": "República de Surinam(Surinam)", "continente": "América", "capital": "Paramaribo"},
{"nombre": "Reino de Tailandia(Tailandia)", "continente": "Asia", "capital": "Bangkok"},
{"nombre": "República Unida de Tanzania(Tanzania)", "continente": "África", "capital": "Dodoma"},
{"nombre": "República de Tayikistán(Tayikistán)", "continente": "Asia", "capital": "Dusambé"},
{"nombre": "República Democrática de Timor Oriental(Timor Oriental)", "continente": "Asia", "capital": "Dili"},
{"nombre": "República Togolesa(Togo)", "continente": "África", "capital": "Lomé"},
{"nombre": "Reino de Tonga(Tonga)", "continente": "Oceanía", "capital": "Nukualofa"},
{"nombre": "República de Trinidad y Tobago(Trinidad y Tobago)", "continente": "América", "capital": "Puerto España"},
{"nombre": "República Tunecina(Túnez)", "continente": "África", "capital": "Ciudad de Túnez"},
{"nombre": "República de Turkmenistán(Turkmenistán)", "continente": "Asia", "capital": "Asjabad"},
{"nombre": "República de Turquía(Turquía)", "continente": "Asia-Europa", "capital": "Ankara"},
{"nombre": "Tuvalu", "continente": "Oceanía", "capital": "Funafuti"},
{"nombre": "Ucrania", "continente": "Europa", "capital": "Kiev"},
{"nombre": "República de Uganda(Uganda)", "continente": "África", "capital": "Kampala"},
{"nombre": "República Oriental del Uruguay(Uruguay)", "continente": "América", "capital": "Montevideo"},
{"nombre": "República de Uzbekistán(Uzbekistán)", "continente": "Asia", "capital": "Taskent"},
{"nombre": "República de Vanuatu(Vanuatu)", "continente": "Oceanía", "capital": "Port Vila"},
{"nombre": "Estado de la Ciudad del Vaticano(Ciudad del Vaticano)", "continente": "Europa", "capital": "Ciudad del Vaticano"},
{"nombre": "República Bolivariana de Venezuela(Venezuela)", "continente": "América", "capital": "Caracas"},
{"nombre": "República Socialista de Vietnam(Vietnam)", "continente": "Asia", "capital": "Hanói"},
{"nombre": "República de Yemen(Yemen)", "continente": "Asia", "capital": "Saná"},
{"nombre": "República de Yibuti(Yibuti)", "continente": "África", "capital": "Ciudad de Yibuti"},
{"nombre": "República de Zambia(Zambia)", "continente": "África", "capital": "Lusaka"},
{"nombre": "República de Zimbabue(Zimbabue)", "continente": "África", "capital": "Harare"}]

@app.get("/Paises/Nombres")
async def nombres():
    return [pais["nombre"] for pais in paises]

@app.get("/Paises/America")
async def america():
    return [pais["nombre"] for pais in paises if pais["continente"] == "América"]

@app.get("/Paises/Asia")
async def asia():
    return [pais["nombre"] for pais in paises if pais["continente"] == "Asia"]

@app.get("/Paises/África")
async def africa():
    return [pais["nombre"] for pais in paises if pais["continente"] == "África"]

@app.get("/Paises/Europa")
async def europa():
    return [pais["nombre"] for pais in paises if pais["continente"] == "Europa"]

@app.get("/Paises/Oceanía")
async def oceania():
    return [pais["nombre"] for pais in paises if pais["continente"] == "Oceanía"]

@app.get("/Paises/Asia-Europa")
async def asia_europa():
    return [pais["nombre"] for pais in paises if pais["continente"] == "Asia-Europa"]

@app.get("/Paises/Nombre-Capital")
async def nombre_capital():
    return [{"nombre": pais["nombre"], "capital": pais["capital"]} for pais in paises]

@app.get("/Paises/America-Capital")
async def america_capital():
    return [{"nombre": pais["nombre"], "capital": pais["capital"]} for pais in paises if pais["continente"] == "América"]

@app.get("/Paises/África-Capital")
async def africa_capital():
    return [{"nombre": pais["nombre"], "capital": pais["capital"]} for pais in paises if pais["continente"] == "África"]